### PR TITLE
Focus on my location

### PR DESCRIPTION
**Pull request by nadavgld**
*Document navigator watch client position on permission
*New crosshair icon
*Zoom to position method

### CODE REVIEW

**Comment by nadavgld** [comment]
image

**Comment by oferb** [comment]
Thanks!
2 comments:
1. I can't seem to find the crosshair when running the site locally. Where is it?  :)
2. We'd like the permission to be asked for the first time when the user presses the crosshair. So a new user entering the page doesn't get the permission notification.

**Comment by nadavgld** [comment]
1. Try to hard reload (CTRL + F5) probably there's a cache issues
2. Changed it to ask permission for the first time whenever the button has clicked

**Comment by oferb** [comment]
Thank you @nadavgld !!

**Pull request merged**
